publication_results_ui <- function() {
  shiny::tagList(
    shiny::div(class="section-card publication-workspace",
      shiny::div(class="section-heading",
        shiny::div(shiny::h2("Publication figures"),
          shiny::p("Turn this analysis into a consistent four-panel figure. Export individual panels or the complete result.")),
        shiny::icon("layer-group")),
      shiny::div(class="publication-controls",
        shiny::selectInput("publicationTransform","Expression display",
          c("log2(x + 1)"="log2","As supplied (already transformed or scaled)"="none")),
        shiny::selectInput("publicationGrouping","Group expression by",
          c("Uploaded labels"="labels","Sample metadata CSV"="samples")),
        shiny::numericInput("publicationSeed","Classification seed",20260908,min=0,max=2147483647,step=1)),
      shiny::conditionalPanel("input.publicationGrouping == 'samples'",
        shiny::fileInput("publicationMetadata","Cell-to-sample metadata",accept=".csv"),
        shiny::p(class="publication-help","CSV columns: cell, sample. Each analyzed cell must have one matching identifier. Samples are shown in the order they first occur in the metadata CSV.")),
      shiny::selectizeInput("publicationInspect","Genes to inspect (up to three)",choices=NULL,multiple=TRUE,
        options=list(maxItems=3,placeholder="Defaults to the first three ranked genes")),
      shiny::p(class="publication-help","Uses 2-50 ranked genes from Output settings. Heatmap values are standardized per gene across cells, then averaged by the chosen group. Expression plots use mapped input values."),
      shiny::div(class="inline-note",shiny::icon("circle-info"),
        shiny::span("Classification uses a cell-level split after gene selection. Cells from the same biological sample may occur in both training and test sets.")),
      shiny::div(class="publication-export-bar",
        shiny::actionButton("generatePublication",shiny::tagList(shiny::icon("wand-magic-sparkles")," Generate publication figure"),class="btn btn-primary"),
        shiny::selectInput("publicationPanel","Export",c("Complete figure"="composite","A - Selection summary"="selection",
          "B - Expression heatmap"="heatmap","C - Gene distributions"="expression","D - Classification"="classification")),
        shiny::selectInput("publicationFormat","Format",c("PDF (vector)"="pdf","PNG (selected dpi)"="png")),
        shiny::conditionalPanel("input.publicationPanel != 'composite' || output.publicationReady",
          shiny::downloadButton("downloadPublication","Download figure",class="btn-secondary"))),
      shiny::conditionalPanel("!output.publicationReady",
        shiny::p(class="publication-help","Generate the complete figure after choosing your settings. Changing a setting clears its preview.")),
      shiny::conditionalPanel("output.publicationReady",
        shiny::div(class="publication-composite",shiny::plotOutput("PublicationComposite",height="880px")))),
    shiny::div(class="publication-panels",
      shiny::div(class="result-card",shiny::h3("A / Selection summary"),shiny::plotOutput("SelectionSummary",height="400px")),
      shiny::div(class="result-card",shiny::h3("B / Expression heatmap"),shiny::plotOutput("HeatMap",height="auto")),
      shiny::div(class="result-card",shiny::h3("C / Gene expression distributions"),shiny::plotOutput("ExpressionDistributions",height="460px")),
      shiny::div(class="result-card",shiny::h3("D / k-NN classification"),shiny::plotOutput("KnnClassifier",height="460px"))),
    shiny::tags$details(class="result-card publication-details",
      shiny::tags$summary("Display groups and gene list"),
      shiny::tableOutput("PublicationGroups"),DT::dataTableOutput("HeatmapList"))
  )
}
